# Programa Ingenias+ Data Science

Como dijimos en clases anteriores, Python tiene implementadas muchas librerias para poder trabajar con datos. En la clase de hoy trabajaremos con una de ellas: `Numpy`.

Antes de comenzar, vamos a hablar un poco de esta libreria o modulo.

**Numpy** es una librería optimizada para realizar cálculos numéricos con vectores y matrices. A diferencia de otros lenguajes de programación, Python no posee en su estructura central la figura de matrices. Eso quiere decir que para poder trabajar con esta estructura de datos deberiamos trabajar con listas de listas. NumPy introduce el concepto de arrays o matrices.

Al ser de código abierto, `numpy` posee una documentación muy amplia que es **SIEMPRE RECOMENDABLE** consultar.

- [Documentacion NumPy](https://devdocs.io/numpy/)

## Clase 4: Introduccion a NumPy

# Ejercicios

1. Crear un arreglo de ceros de longitud 12
2. Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
3. Crear un arreglo que tenga los números del 10 al 49
4. Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
5. Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
6. Calcular la media de un arreglo usando np.sum
7. Calcular la varianza de un arreglo usando np.sum y np.mean
8. Crear un array de números aleatorios usando np.random.randn.


In [64]:
#Importar la libreria a utilizar
import numpy as np

In [65]:
# Ejercicio 1
# Crear un arreglo de ceros de longitud 12
array1 = np.zeros (12)
array1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [66]:
# Ejercicico 2
# Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
array2 = np.zeros (10)
array2 [4] = 10
array2

array([ 0.,  0.,  0.,  0., 10.,  0.,  0.,  0.,  0.,  0.])

In [67]:
# Ejercicico 3
# Crear un arreglo que tenga los números del 10 al 49
array3 = np.arange(10,50)
array3

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [68]:
# Ejercicio 4
# Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
array4_2D = np.arange(9).reshape(3,3)
array4_2D

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [69]:
# Ejercicio 5
# Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
# 5.1 Crear el arreglo de números aleatorios
array5 = np.random.randint ( 0, 100, size=100)
array5

array([44, 75, 23, 62, 48,  6, 72, 29, 42, 96, 79, 36, 90, 64,  7, 22, 35,
       27, 12, 77, 79,  0, 67, 69, 36,  3, 47, 80, 92, 28, 37, 12, 53, 31,
       68, 25, 32,  4, 28, 37, 70,  0, 68, 30, 75, 34, 81,  0, 33,  4, 32,
       81, 18,  6, 36, 41, 64, 13, 75,  7, 23, 57, 52,  7, 23, 80, 39, 50,
       26, 21, 19, 18, 71, 80, 85, 24, 98, 57, 62, 38, 49, 46,  4, 51, 75,
       98, 28, 94, 82, 88, 25, 71, 15, 91, 32, 29,  0, 19, 29, 72])

In [70]:
# 5.2 Calcular la media
meanarray5 = np.mean (array5)
meanarray5

44.7

In [71]:
# 5.3 Calcular la varianza
vararray5 = np.var(array5)
vararray5

794.13

In [72]:
# Ejercicio 6
# Calcular la media de un arreglo usando np.sum
# 6.1 Sumar el total de los elementos
sumarray3 = np.sum(array3)
sumarray3

1180

In [73]:
# 6.2 Obtener la cantidad de elementos
lenarray3 = len(array3)
lenarray3

40

In [74]:
 # 6.3 Calcular la media
mediaarray3 = sumarray3 / lenarray3
mediaarray3

29.5

In [75]:
#Ejercicio 7
# Calcular la varianza de un arreglo usando np.sum y np.mean
# 7.1 Calcular la media
meanarray3 = np.mean(array3)
meanarray3


29.5

In [76]:
# 7.2 Obtener las desviaciones
desviaciones = array3 - meanarray3
desviaciones

array([-19.5, -18.5, -17.5, -16.5, -15.5, -14.5, -13.5, -12.5, -11.5,
       -10.5,  -9.5,  -8.5,  -7.5,  -6.5,  -5.5,  -4.5,  -3.5,  -2.5,
        -1.5,  -0.5,   0.5,   1.5,   2.5,   3.5,   4.5,   5.5,   6.5,
         7.5,   8.5,   9.5,  10.5,  11.5,  12.5,  13.5,  14.5,  15.5,
        16.5,  17.5,  18.5,  19.5])

In [77]:
# 7.3 Elevar al cuadrado las desviaciones
desviacionescuadrado = desviaciones**2
desviacionescuadrado

array([3.8025e+02, 3.4225e+02, 3.0625e+02, 2.7225e+02, 2.4025e+02,
       2.1025e+02, 1.8225e+02, 1.5625e+02, 1.3225e+02, 1.1025e+02,
       9.0250e+01, 7.2250e+01, 5.6250e+01, 4.2250e+01, 3.0250e+01,
       2.0250e+01, 1.2250e+01, 6.2500e+00, 2.2500e+00, 2.5000e-01,
       2.5000e-01, 2.2500e+00, 6.2500e+00, 1.2250e+01, 2.0250e+01,
       3.0250e+01, 4.2250e+01, 5.6250e+01, 7.2250e+01, 9.0250e+01,
       1.1025e+02, 1.3225e+02, 1.5625e+02, 1.8225e+02, 2.1025e+02,
       2.4025e+02, 2.7225e+02, 3.0625e+02, 3.4225e+02, 3.8025e+02])

In [78]:
# 7.4 Calcular la varianza. Calcular la suma de las desviaciones al cuadrado y dividir por la cantidad de elementos
varianzaarray3 = np.sum(desviacionescuadrado) / len(array3)
varianzaarray3

133.25

In [79]:
# Ejercicio 8
# Crear un array de números aleatorios usando np.random.randn.
# 8.1 Crear array 1D
array8 = np.random.rand (10)
array8

array([0.32348979, 0.7534511 , 0.98131328, 0.64079017, 0.09941188,
       0.21477185, 0.99695272, 0.78678702, 0.56456255, 0.58568461])

In [80]:
#8.2 Crear array 2D
array8_2D = np.random.rand (2,3)
array8_2D

array([[0.85680743, 0.28739512, 0.62565729],
       [0.08136867, 0.92145312, 0.12948788]])